name: "Release"

on:
  release:
    types: [published]

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.2.2

      - name: Extract version from release
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Adjust version number
        shell: bash
        run: |
          yq -i -o json '.version="${{ env.VERSION }}"' \
            "${{ github.workspace }}/custom_components/meteo_lt/manifest.json"

      - name: ZIP the integration directory
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/meteo_lt"
          zip meteo_lt-${{ env.VERSION }}.zip -r ./

      - name: Upload the ZIP file to the release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: ${{ github.workspace }}/custom_components/meteo_lt/meteo_lt-${{ env.VERSION }}.zip