name: "Release"

on:
  release:
    types: [published]

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5.0.0

      - name: Extract version from release
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Adjust version number
        shell: bash
        run: |
          MANIFEST=$(find "${{ github.workspace }}/custom_components" -maxdepth 2 -type f -name manifest.json -print -quit)
          if [ -z "$MANIFEST" ]; then
            echo "ERROR: manifest.json not found under custom_components" >&2
            ls -al "${{ github.workspace }}/custom_components" || true
            exit 1
          fi
          echo "Found manifest: $MANIFEST"
          yq -i -o json '.version="${{ env.VERSION }}"' "$MANIFEST"

      - name: ZIP the integration directory
        shell: bash
        run: |
          MANIFEST=$(find "${{ github.workspace }}/custom_components" -maxdepth 2 -type f -name manifest.json -print -quit)
          DIR=$(dirname "$MANIFEST")
          NAME=$(basename "$DIR")
          echo "Zipping integration in $DIR as $NAME-${{ env.VERSION }}.zip"
          cd "$DIR"
          zip "$NAME-${{ env.VERSION }}.zip" -r ./
          ZIP_PATH="$DIR/$NAME-${{ env.VERSION }}.zip"
          echo "ZIP_PATH=$ZIP_PATH" >> $GITHUB_ENV
          echo "Created $ZIP_PATH"
          ls -l "$ZIP_PATH" || true

      - name: Upload the ZIP file to the release
        uses: softprops/action-gh-release@v2.4.1
        with:
          files: ${{ env.ZIP_PATH }}
          overwrite_files: true
